---
- name: Connect ResearchDrive
  hosts: rdrive
  vars: 
    connect_script_name: connect-research-drive.ps1
    disconnect_script_name: disconnect-research-drive.ps1
  gather_facts: false
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300
    
    - name: Set an environment variable for the Azure Key Vault name
      win_environment:
        state: present
        name: "VREResearchDriveKV"
        value: "{{ vre_kv }}"
        level: machine

    - name: Set an environment variable for the VRE instance
      win_environment:
        state: present
        name: "VREinstance"
        value: "{{ vre_instance }}"
        level: machine
    
    - name: Copy connect Powershell script to target machine
      ansible.windows.win_copy:
        src: files/{{ connect_script_name }}
        dest: C:\Packages\{{ connect_script_name }}
        force: yes

    - name: Create file to run Powershell script on startup
      ansible.windows.win_copy:
        content: |
          @echo off
          PowerShell -ExecutionPolicy Unrestricted C:\Packages\{{ connect_script_name }} >> "%TEMP%\StartupLog-{{ connect_script_name }}.txt" 2>&1
        dest: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\startup-{{ connect_script_name }}.cmd
        force: yes

    - name: Copy disconnect Powershell script to target machine
      ansible.windows.win_copy:
        src: files/{{ disconnect_script_name }}
        dest: C:\Packages\{{ disconnect_script_name }}
        force: yes

    - name: Copy group policy files
      ansible.windows.win_copy:
        src: files/gpo/
        dest: C:\Windows\System32\GroupPolicy
        force: yes

    - name: Run script to get username and password from key vault and mount Research Drive
      ansible.windows.win_shell: C:\Packages\{{ connect_script_name }} -workspaceKV {{ vre_kv }} -instance {{ vre_instance }}
    
    - name: Ensure a desktop shortcut to the network drive is created using chocolatey helpers
      ansible.windows.win_shell: Import-Module $env:ChocolateyInstall\helpers\chocolateyInstaller.psm1; Install-ChocolateyShortcut -ShortcutFilePath "C:\Users\Public\Public Desktop\Research Drive.lnk" -TargetPath R:\