---
- name: Install MPC using chocolatey
  hosts: mpc_1.9.16
  gather_facts: false
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300
    - name: Install MPC
      win_shell: choco install mpc-hc-clsid2 --version=1.9.16
    - name: Ensure a desktop shortcut for MPC is created using chocolatey helpers
      win_shell: Import-Module "$env:ChocolateyInstall\helpers\chocolateyInstaller.psm1"; Install-ChocolateyShortcut -ShortcutFilePath "C:\Users\Public\Public Desktop\MPC.lnk" -TargetPath "C:\Program Files\MPC-HC\mpc-hc64.exe"
