# This is a GitLab CI configuration to build the project as a docker image
# The file is generic enough to be dropped in a project containing a working Dockerfile
# Author: Florent CHAUVEAU <florent.chauveau@gmail.com>
# Mentioned here: https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/

# do not use "latest" here, if you want this to work in the future
image: docker:20

stages:
  - build-and-push

build-and-push:
  stage: build-and-push
  variables:
    IMAGE_TAG: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$DOCKERFILE_TO_BUILD:$CI_COMMIT_SHORT_SHA"
  script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f "$DOCKERFILE_TO_BUILD.Dockerfile" .
    - docker push $IMAGE_TAG
  only:
    variables:
      - $DOCKERFILE_TO_BUILD != "none"